### ISSUE TITLE
Issue with v1.3.0 Policies

### ISSUE THREAD

**Issue by yinwhm12** [aidtechnology/hgf-k8s-workshop#12]
I found  "AdminPrincipal: Role.MEMBER"(the Policies is old, appeared in v1.0.0) in configtx.yaml, and I changed the Policies to v1.3.0 in configtx.yaml,as below like these codes:
```       
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
```

However,I failed to create the channel, error info:
![image](https://user-images.githubusercontent.com/25929417/52847568-8082b700-3147-11e9-8d4e-6fa14b4cfacf.png)

So, is the Policies always "AdminPrincipal: Role.MEMBER"?
I‘m so confused, I need your responds sincerely. TY
